version: '3.8'

services:
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: drone-delivery
    environment:
      MONGO_DB_URL: mongodb://db_mongo
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "start:prod"]


volumes:
  mongodata: 